### ISSUE TITLE
新年快乐=  =

### ISSUE THREAD

**Issue by lsz7575** [caoli5288/ProtectPlugin#2]
很抱歉的打搅一下- =我非常喜欢你这个插件。。但是在KCauldron version 1.7.10-1448.133 会报个错误。弱弱的问一下，容易改的话能不能帮忙改一下或者给我一个不报错的版本。。
邮箱75750388@qq.com  谢谢。。
[02:31:03] [Server thread/ERROR]: Error occurred while enabling ProtectPlugin v0.3.0 (Is it up to date?)
java.lang.ExceptionInInitializerError
    at com.mengcraft.protect.ProtectPlugin.onEnable(ProtectPlugin.java:75) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:1.7.10-1448.133]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:1.7.10-1448.133]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:1.7.10-1448.133]
    at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:415) [CraftServer.class:1.7.10-1448.133]
    at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:349) [CraftServer.class:1.7.10-1448.133]
    at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:511) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:485) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:445) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336) [lt.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.lang.NumberFormatException: For input string: "120.24.4.118"
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_72]
    at java.lang.Long.parseLong(Long.java:589) ~[?:1.8.0_72]
    at java.lang.Long.<init>(Long.java:965) ~[?:1.8.0_72]
    at com.mengcraft.protect.manager.PlayerManager.parse(PlayerManager.java:95) ~[?:?]
    at com.mengcraft.protect.manager.PlayerManager.parse(PlayerManager.java:88) ~[?:?]
    at com.mengcraft.protect.manager.PlayerManager.readFile(PlayerManager.java:80) ~[?:?]
    at com.mengcraft.protect.manager.PlayerManager.<init>(PlayerManager.java:32) ~[?:?]
    at com.mengcraft.protect.manager.PlayerManager.<clinit>(PlayerManager.java:21) ~[?:?]
    ... 12 more
新年快乐~~~~~~~~~~~~~~~~~~~~~

**Comment by Cnly** [comment]
你用的插件是什么版本？

**Comment by lsz7575** [comment]
ProtectPlugin v0.3.0      0.3.0版本的   @Cnly

**Comment by Cnly** [comment]
0.3.0 不是Snapshot 挺旧了吧

**Comment by lsz7575** [comment]
mcbbs上,下的，我不知道上哪下新的。。下了源码，下了编译工具整半天，还是不会编译  @Cnly

**Comment by Cnly** [comment]
http://ci.mengcraft.com:8080/

**Comment by lsz7575** [comment]
@Cnly ok了。非常感谢，祝你生活愉快~  ~^o^~

**Comment by Cnly** [comment]
ok 你把这个issue close了吧。
